### ISSUE TITLE
Some colors are not identified as "main" and the wrong color palette is generated

### ISSUE THREAD

**Issue by e-farias** [soybeanjs/color-palette#1]
I'm trying to create a color input that generates a theme. But some colors are not identified as "main" and the wrong color palette is generated.

Example:

```
import { getColorPalette, getColorName } from "@soybeanjs/color-palette"

const color = "#00ffbf"
const palette = getColorPalette(color, getColorName(color))
```

![WhatsApp Image 2024-06-03 at 03 15 15](https://github.com/soybeanjs/color-palette/assets/43360593/c666ad26-4bc1-48e9-9be1-4065fbec2744)

![WhatsApp Image 2024-06-03 at 03 15 48](https://github.com/soybeanjs/color-palette/assets/43360593/991a75ef-befc-4116-b5fc-ee1f241d77da)

Is there a configuration missing?

**Comment by honghuangdc** [comment]
I forget to update this repository, please see this correct code in [here](https://github.com/soybeanjs/soybean-admin/blob/main/packages/color/src/palette/index.ts), I'll update code later.

use function `getRecommendedColorPalette`

**Comment by honghuangdc** [comment]
now you can use v0.1.0, it fix the error. 9fed996

**Comment by honghuangdc** [comment]
install 0.1.1
